language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - "pip install --upgrade setuptools pip"
  - "pip install -r requirements_test.txt"
  - "pip install ."
script:
  - "pytest --cov=highdicom --cov-fail-under=80 tests"
  - "flake8 --exclude='bin,build,.eggs,src/highdicom/_*'"
  - "mypy src/highdicom tests"
