"""Value types used within images and volumes."""

# Dictionary mapping DCM VRs to appropriate SQLite types
_DCM_SQL_TYPE_MAP = {
    'CS': 'VARCHAR',
    'DS': 'REAL',
    'FD': 'REAL',
    'FL': 'REAL',
    'IS': 'INTEGER',
    'LO': 'TEXT',
    'LT': 'TEXT',
    'PN': 'TEXT',
    'SH': 'TEXT',
    'SL': 'INTEGER',
    'SS': 'INTEGER',
    'ST': 'TEXT',
    'UI': 'TEXT',
    'UL': 'INTEGER',
    'UR': 'TEXT',
    'US or SS': 'INTEGER',
    'US': 'INTEGER',
    'UT': 'TEXT',
}
_DCM_PYTHON_TYPE_MAP = {
    'CS': str,
    'DS': float,
    'FD': float,
    'FL': float,
    'IS': int,
    'LO': str,
    'LT': str,
    'PN': str,
    'SH': str,
    'SL': int,
    'SS': int,
    'ST': str,
    'UI': str,
    'UL': int,
    'UR': str,
    'US or SS': int,
    'US': int,
    'UT': str,
}
